apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600s"
  name: websocket-ingress-ws
  namespace: system-websocket
spec:
  ingressClassName: nginx
  rules:
    - host: socket.huoxingqianli.cn
      http:
        paths:
          - backend:
              service:
                name: service-websocket-svc
                port:
                  number: 8001
            path: /
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket-ingress-api
  namespace: system-websocket
spec:
  ingressClassName: nginx
  rules:
    - host: socket-api.huoxingqianli.cn
      http:
        paths:
          - backend:
              service:
                name: service-websocket-svc
                port:
                  number: 3000
            path: /
            pathType: Prefix