# NameSpace
apiVersion: v1
kind: Namespace
metadata:
  name: system-websocket
---
# ServiceAccessSecret
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: websocket
  name: websocket-secret
  namespace: system-websocket
type: kubernetes.io/service-account-token
---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: websocket
  namespace: system-websocket
secrets:
  - name: websocket-secret
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: websocket
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: websocket
    namespace: system-websocket
---
# Channel CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webstocket-channel.service.manager
spec:
  group: service.manager
  scope: Namespaced
  names:
    kind: WebStocketChannel
    plural: webstocket-channel
    shortNames:
      - "wsc"
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # 通道秘钥
                channelKey:
                  type: string
                  default:
                # 事件
                event:
                  type: object
                  properties:
                    onOpen:
                      type: array
                      items:
                        type: object
                        properties:
                          # URl
                          url:
                            type: string
                          # 超时时间
                          timeout:
                            type: integer
                            default: 30
                          # 请求方式
                          method:
                            type: string
                            default: POST
                    onMessage:
                      type: array
                      items:
                        type: object
                        properties:
                          # URl
                          url:
                            type: string
                          # 超时时间
                          timeout:
                            type: integer
                            default: 30
                          # 请求方式
                          method:
                            type: string
                            default: POST
                    onClose:
                      type: array
                      items:
                        type: object
                        properties:
                          # URl
                          url:
                            type: string
                          # 超时时间
                          timeout:
                            type: integer
                            default: 30
                          # 请求方式
                          method:
                            type: string
                            default: POST
            status:
              type: object
              properties:
                # 状态
                status:
                  type: string
                  default: padding
      additionalPrinterColumns:
        - name: 状态
          type: string
          description: 任务状态
          jsonPath: ".status.status"
---
# 连接信息存储
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websocket-connection.service.manager
spec:
  group: service.manager
  scope: Namespaced
  names:
    kind: WebSocketConnection
    plural: websocket-connection
    shortNames:
      - "wscnn"
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # 节点
                node:
                  type: string
                  default:
                # 通道
                channel:
                  type: string
                  default:
                # 连接URI
                uri:
                  type: string
                  default:
                # 连接来源
                origin:
                  type: string
                  default:
            status:
              type: object
              properties:
                # 状态
                status:
                  type: string
                  default: padding
      additionalPrinterColumns:
        - name: 状态
          type: string
          description: 任务状态
          jsonPath: ".status.status"
---
# 连接任务
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websocket-connection-task.service.manager
spec:
  group: service.manager
  scope: Namespaced
  names:
    kind: WebSocketConnectionTask
    plural: websocket-connection-task
    shortNames:
      - "wscnt"
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # 节点
                node:
                  type: string
                  default:
                # 连接ID
                connectionId:
                  type: string
                  default:
                # 任务类型
                task:
                  type: string
                  default: sendMessage
                # 任务内容
                body:
                  type: string
                  default:
            status:
              type: object
              properties:
                # 状态
                status:
                  type: string
                  default: padding
      additionalPrinterColumns:
        - name: 状态
          type: string
          description: 任务状态
          jsonPath: ".status.status"
---
# Websocket Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
  namespace: system-websocket
  labels:
    app: websocket
spec:
  selector:
    matchLabels:
      app: websocket
  replicas: 1
  template:
    metadata:
      labels:
        app: websocket
    spec:
      volumes:
        - name: websocket-secret-volume
          secret:
            secretName: websocket-secret
      containers:
        - name: websocket-container
          image: registry.cn-hangzhou.aliyuncs.com/huoxingqianli/websocket:v0.0.1
          #          image: nginx:alpine
          volumeMounts:
            - mountPath: /etc/token
              name: pipeline-secret-volume
              readOnly: true
              subPath: token
# 服务暴露
---
apiVersion: v1
kind: Service
metadata:
  name: service-websocket-svc
  namespace: system-websocket
  labels:
    app: websocket
spec:
  selector:
    app: websocket
  # 访问方式 ClusterIP NodePort LoadBalancer
  type: ClusterIP
  ports:
    - name: ws-8001
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: api-3000
      protocol: TCP
      port: 3000
      targetPort: 3000